name: Upload to IPFS on Push (nft.storage)

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install nft.storage CLI
      run: npm install -g nft.storage

    - name: Upload to nft.storage
      env:
        NFT_STORAGE_TOKEN: ${{ secrets.NFT_STORAGE_TOKEN }}
      run: |
        nft.storage upload ./ --recursive --name "Planetary Restoration Archive - $(date +%Y-%m-%d)"
