name: Upload to IPFS

on:
  push:
    branches:
      - main  # or your working branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or another supported version

      - name: Install dependencies
        run: npm install -g nft.storage

      - name: Upload folder to IPFS
        env:
          NFT_STORAGE_TOKEN: ${{ secrets.NFT_STORAGE_API_KEY }}
        run: |
          # Example: Upload "public" folder
          nftstorage store-directory . > upload_output.json
          echo "Upload complete. CID saved to upload_output.json"
