name: Upload to IPFS

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip the archive
        run: zip -r archive.zip planetary-restoration-archive

      - name: Upload to IPFS via NFT.Storage
        run: |
          curl -X POST https://api.nft.storage/upload \
            -H "Authorization: Bearer ${{ secrets.NFT_STORAGE_KEY }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@archive.zip"
